server:
  port: 9090
spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
      
app:
  messages:
    welcomeMsg: Welcome To User Management System..!!
    userRegSucc: User Registration Successfull...!!
    userRegFaild: Faild To Register
  
        